### PR TITLE
Fix: Use base16 to convert pci sriov_vf_device

### LINKED ISSUE #761: Error obtaining PCI device info
## Host operating system
Linux XXX 5.15.0-136-generic prometheus/node_exporter#147-Ubuntu SMP Sat Mar 15 15:53:30 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

## Node exporter version
node_exporter, version 1.10.2 (branch: HEAD, revision: 654f19dee6a0c41de78a8d6d870e8c742cdb43b9)
  build user:       root@b29b4019149a
  build date:       20251025-20:05:32
  go version:       go1.25.3
  platform:         linux/amd64
  tags:             unknown

## Description

Added --collector.pcidevice to startup options

node exporter reports the following in the logs and does not return pcidevice information

```
node_exporter[3784071]: time=2025-10-30T07:34:27.975Z level=ERROR source=collector.go:168 msg="collector failed" name=pcidevice duration_seconds=0.050285948 err="error obtaining PCI device info: failed to parse SR-IOV integer \"101e\": strconv.ParseUint: parsing \"101e\": invalid syntax"
```

### PR DESCRIPTION
**Pull request by jj-asama**
Fixes #761 

Also makes the error messages more verbose.

### CODE REVIEW

File: sysfs/pci_device.go [hunk 1]
```diff
@@ -317,55 +317,55 @@ func (fs FS) parsePciDevice(name string) (*PciDevice, error) {
...
 			if err != nil {
-				return nil, fmt.Errorf("failed to parse SR-IOV integer %q: %w", valueStr, err)
+				return nil, fmt.Errorf("failed to parse SR-IOV totalvfs %q %s: %w", valueStr, device.Location, err)
 			}
 			v := uint32(value)
 			device.SriovTotalvfs = &v
 
 		case "sriov_vf_device":
-			value, err := strconv.ParseUint(valueStr, 10, 32)
+			value, err := strconv.ParseUint(valueStr, 16, 32)
```
Comment (jj-asama) [inline sysfs/pci_device.go]: @SuperQ this fixes #761 . Value in this file doesn't have 0x prefix which led to the mistake.
