### PR TITLE
Make tests platform independent

### LINKED ISSUE #13: Test don't pass on OSX 10.10.5
--- FAIL: TestSelf (0.00s)
    	proc_test.go:13: could not read /proc: stat /proc: no such file or directory
    --- FAIL: TestFileDescriptors (0.00s)
    	proc_test.go:102: could not read /proc: stat /proc: no such file or directory
    --- FAIL: TestFileDescriptorTargets (0.00s)
    	proc_test.go:149: could not read /proc: stat /proc: no such file or directory
    FAIL
    FAIL	github.comcast.com/vbo/derp-4/vendor/github.com/prometheus/procfs	0.013s

### PR DESCRIPTION
**Pull request by grobie**
Fixes #13.

@brian-brazil @fabxc @matthiasr

### CODE REVIEW

File: proc.go [hunk 1]
```diff
@@ -24,9 +24,13 @@ func (p Procs) Len() int           { return len(p) }
 func (p Procs) Swap(i, j int)      { p[i], p[j] = p[j], p[i] }
 func (p Procs) Less(i, j int) bool { return p[i].PID < p[j].PID }
 
-// Self returns a process for the current process.
+// Self returns a process for the current process read via /proc/self.
 func Self() (Proc, error) {
-	return NewProc(os.Getpid())
+	fs, err := NewFS(DefaultMountPoint)
+	if err != nil {
+		return Proc{}, err
```
Comment (brian-brazil) [inline proc.go]: Why return `Proc{}` rather than `nil`?

Comment (fabxc) [inline proc.go]: Because the return type is not a pointer or an interface.

**Comment by brian-brazil** [comment]
:+1:
